bitextor/warc2text

- README.md
- src/CMakeLists.txt
- src/record.cc
- src/util.cc
- src/util.hh
- src/warcpreprocessor.cc
* Use uchardet to detect encoding of documents after HTML cleaning
* The detected encoding is preferred over the charset found in HTTP header
* If no encoding is found/detect, document is removed
> Use uchardet to detect document encoding

- src/html.cc
- src/html.hh
- src/record.cc
- src/record.hh
- src/util.cc
- src/util.hh
- src/warcpreprocessor.cc
- src/warcpreprocessor.hh
- src/xh_scanner.cc
- src/xh_scanner.hh
- tags_filters
- warc2text_main.cc
* Format of the filters have the following format:
`tag <tab> attribute <tab> value <tab> value ...`
For example, `meta name translation-stats` will filter out documents that contain: `<meta name="translation-stats" ... >`.
The filter functionality checks that the value of `name` attribute contains the specified string, not that they are equal. So, the filter `meta name translation` would also eliminate a document with `<meta name="translation-stats" ...>`.
* The documents that contain filter tags are not outputted, and a message with the URL of the filtered record is shown on the console
* `--tag-filter` to pass the filters file
> Filter out documents that contain tags that could indicate machine translation

- README.md
- src/bilangwriter.cc
- src/bilangwriter.hh
- src/util.cc
- src/util.hh
- src/warcpreprocessor.cc
- src/warcpreprocessor.hh
- src/warcreader.cc
- src/warcreader.hh
- warc2text_main.cc
Enable this functionality by providing a filename for WARC output via `--pdfpass` option
> Write PDF records to a separate WARC file

- src/html.cc
- src/util.cc
- src/util.hh
- src/warcpreprocessor.cc
- src/warcpreprocessor.hh
- warc2text_main.cc
New command line options from @jelmervdl fork:
* `-s` to only output errors
* `--invert-tag-filters` to only output documents that have matches from tag filters
Also, new debug message showing the matched strings
> New options

- README.md
- debug-filters.sh
- src/util.cc
- src/util.hh
I've been annotating Minas' tag filter file to add notes about what rules filter what and why they're in there. It's probably easy if the file with annotations can be used as-is, and doesn't need to be processed through `sed` or something.
This merge request also contains some more noisy error reporting for when an unparseable line is encountered. Previously this would stop the parsing of the filter list silently. Now it will raise a warning but continue with the next line.
Oh and I removed the dead code of readTagFilters.
> Allow comments in tag filter file

- src/util.cc
- src/util.hh
Sorry about this.
Clang was happy with the brace initializer for regex, but gcc/9 on CSD3 wasn't.
> Fix compilation issue with gcc.

- src/warcpreprocessor.cc
Ugly workaround for #16 so I can continue processing warcs.
For ParaCrawl this solution is, I think, sufficient. I do not expect troves of bilingual texts in these massive pdfs, rather just a bunch of scanned books with at most not-too-great OCR applied to them.
> Skip large pdfs

- src/warcpreprocessor.cc
Quick follow-up for #17 that removes the StringPiece size check all together, and will tell you any pdfs got skipped.
> Remove work-around for StringPiece confusion.

- src/CMakeLists.txt
- src/html.cc
- src/record.cc
- src/util.cc
- src/util.hh
- src/zipreader.cc
- src/zipreader.hh
I've replaced the zip extraction logic with some more C++-ish code that doesn't crash or leak on the test files I've used.
(I've also taken this opportunity to replace two string functions that I previously pushed with functions that are already available in boost::algorithm.)
Zip reading is now working better with this patch. However, the output of the extracted odts isn't great. I've attached a warc file with two odts. One fails in the HTML parser, the other makes it through but has no line breaks at all in the text output.
Maybe some simple changes to the html parser will make it more compatible with odts. I haven't looked into that yet.
[zip.warc.gz](https://github.com/bitextor/warc2text/files/5836745/zip.warc.gz)
Edit: Also attaching a test warc with a couple of office document …
> Replace zip extraction

- src/warcpreprocessor.cc
One more pull-request, sorry! But I kind of forgot about what to do with those exceptions I introduced…
This skips over records that have a zip file that cannot be read. In most cases I think it's just a miss-mimetyped document that isn't really a zip file.
> Ignore zip errors

- src/bilangwriter.cc
- src/bilangwriter.hh
- src/lang.cc
- src/lang.hh
- src/record.cc
- src/record.hh
- src/util.cc
- src/warcpreprocessor.cc
- src/warcpreprocessor.hh
- warc2text_main.cc
CLD2 detects top 3 languages of the document and returns a vector of chunks corresponding to different languages. These chunks are joined to generate one record per language; and each record is written to the corresponding file on disk.
This functionality is enabled with `--multilang`
> Use CLD2 extended detection method to detect multiple languages in a single document 

- README.md
- src/util.cc
- src/util.hh
- src/warcpreprocessor.cc
- src/warcpreprocessor.hh
- warc2text_main.cc
I tried to keep it consistent with the tag filter already implemented.
Basically it allows you to write regular expressions that match parts of the url. If the url matches, the document is filtered. Fairly simple.
URL filter format is a single regular expression per line. Empty lines and line starting with `#` are allowed, just like in the tag filter file. Parse errors result in a warning and the line being skipped.
> Add url filter, similar to the tag filter we use for MT

- .gitignore
- src/entities.cc
- src/record.cc
- src/record.hh
- src/util.cc
- src/util.hh
- src/warcpreprocessor.cc
- src/warcpreprocessor.hh
- src/zipreader.cc
- src/zipreader.hh
- warc2text_main.cc
Special characters that have no business being in URLs will be escaped (i.e. spaces will become `%20`)
Reserved characters that normally have a purpose, such as `/`, `?`, `&`, `=`, `#`, etc. will be left as is, because it is not trivial to detect when they are being used for their purpose or if they are a part of the data. Unless escaping those is also important @jelmervdl ?
The flag to activate this is `--encode-urls`
> Add --encode-urls option to deal with unescaped chars in URLs

- src/warcpreprocessor.cc
I messed up earlier and marked them as debug. This change marks them as info, the same level as omissions due to the tag filter.
> Mark url filter notices as level "info"

- src/CMakeLists.txt
- src/html.cc
- src/util.cc
- src/util.hh
- src/warcpreprocessor.cc
- src/warcpreprocessor.hh
My url filter implementation is really slowing down warc2text right now, being the slowest part of the process after decompression (no 1) and uchardet (no 2) 😅
I've tried a number of optimisations, and this combination seems to be the fastest:
- Skip storing submatches: saves a lot of tiny allocations
- Combine all regular expressions into a large one for the URL filter
- Switch out std::regex for boost::regex (which seems to be quite a bit better at optimising)
Runtimes on a single wide6 warc:
| Setting | Time |
| --- | ---: |
| master with url filter* (35 entries) | 1:15 |
| master with url filter** (1 entry) | 0:52 |
| master without url filter | 0:47 |
| this branch with url filter (35 entries) | 0:50 |
| this branch with url filter** (1 entry) | 0:48 |
*) The url filter list I used …
> Optimize regex filters

- src/record.cc
PDF processing generates these plain text documents. But I noticed that when I feed these warcs with just plain/text documents, parsing will fail and the document will be dropped.
This change does assume that there are generally no html documents (or anything else that goes through `processHTML`) served with text/plain; there's no heuristic for determining whether something is plain text or not.
> Don't parse text/plain as HTML

- README.md
- src/bilangwriter.cc
- src/bilangwriter.hh
- src/util.cc
- src/util.hh
- src/warcpreprocessor.cc
- src/warcpreprocessor.hh
- warc2text_main.cc
New feature which identifies paragraphs if flag `--paragraph-identification` is set. It adds an identifier for each extracted paragraph from the HTML before being base64-encoded. If `--paragraph-identification` is set, when base64-decoded, it has to be taken into account that the document has been encoded "twice" (if the text is going to be processes, the text will have to be split and get the first element).
The format is: `<document content><tab><paragraph identifier>`. The paragraph identifier is a number which starts at 0.
> Paragraph identification

- .gitmodules
- CMakeLists.txt
- README.md
- src/CMakeLists.txt
- src/bilangwriter.cc
- src/bilangwriter.hh
- src/lang.cc
- src/lang.hh
- src/lang_cld2.cc
- src/lang_fasttext.cc
- src/record.cc
- src/record.hh
- src/warcpreprocessor.cc
- src/warcpreprocessor.hh
- warc2text_main.cc
This takes @kpu's work on using fasttext but adds it as an option alongside cld2. To make it easier to compare the two (or more, if we integrate more classifiers).
Currently in draft just to notify other followers of this work. The cld2 code path triggers a EXC_BAD_ACCESS at some point when writing to the url.gz file? It's a bit of a mystery, hence draft.
Edit for posterity:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x68)
frame #0: 0x00007ff80c8d6d13 libsystem_c.dylib`flockfile + 18
libsystem_c.dylib`flockfile:
->  0x7ff80c8d6d13 <+18>: movq   0x68(%rbx), %rdi
0x7ff80c8d6d17 <+22>: addq   $0x8, %rdi
0x7ff80c8d6d1b <+26>: callq  0x7ff80c94691e            ; symbol stub for: pthread_mutex_lock
0x7ff80c8d6d20 <+31>: callq  0x7ff80c94643e …
```
> Add fasttext as an option alongside cld2

- CMakeLists.txt
- README.md
- src/bilangwriter.cc
- src/bilangwriter.hh
- src/record.cc
- src/record.hh
- src/util.cc
- src/util.hh
- src/warcpreprocessor.cc
- src/warcpreprocessor.hh
- src/warcreader.cc
- src/warcreader.hh
- warc2text_main.cc
This is mostly to do some metadata analysis of the warcs, but could be a starting point for #34 as well.
For metadata I'm considering trying out [writing to parquet directly](https://arrow.apache.org/docs/cpp/parquet.html). But since warc2text is run in parallel we'd still need to merge parquet files together before doing any analysis. So maybe jsonl is sufficient for this stage. And then we ingest all of those together into a massive parquet file for queries later.
Current output: each line contains a JSON object that consists of:
- `f`: filename of warc file
- `o`: byte offset of record in warc file
- `s`: warc file record size
- `rs`: byte size of record payload (uncompressed)
- `ps`: byte size of text only payload (so compare this against `rs` and you should get amount of HTML …
> Add `--jsonl` option

- README.md
- src/bilangwriter.cc
- src/bilangwriter.hh
- src/lang.cc
- src/lang.hh
- src/record.cc
- src/record.hh
- src/util.cc
- src/warcpreprocessor.cc
- src/warcpreprocessor.hh
- warc2text_main.cc
As we've been [discussing](https://github.com/orgs/hplt-project/discussions/1) in HPLT, our first stage of the pipeline will probably be just an HTML extraction and metadata form WARCs. Excluding text extraction from HTML and language identification.
We firstly discussed that we may create a separate fork to do all of these things, but since I've been able to write the changes in a more or less clean way, with pluggable CLI options, I think it is reasonable to keep it in the main branch. The list of features this PR adds:
- `--classifier skip` to skip language identification entirely. When this is used, warc2text will write the output files directly in the output folder without any language specific folder. In the case of JSON output, the `l` filed will be omitted.
- …
> warc2html changes

- src/bilangwriter.cc
- src/bilangwriter.hh
- warc2text_main.cc
Now the user can choose between ZSTD or GZIP compression format (GZIP being default) and compression level. This change is made upon #50 because it is a feature that we may really need if we use HTML output, that is considerably taking more space than only text.
The code has been changed to use `boost::filtering_streambuf` to easily switch between algorithms, removing the old `GzipWriter` class that was handling compression more manually.
To see the real differences of this PR see https://github.com/bitextor/warc2text/pull/51/commits/53709d06456b8e357fe93ce6ebb12b078ecd3084
> ZSTD compression and compression level support

- README.md
- src/bilangwriter.cc
- src/bilangwriter.hh
- warc2text_main.cc
This changes the behaviour of the --jsonl option. Now the option only changes the output format to JSONL but not the output location. To write JSONL with all the metadata and text to stdout use along with --stdout. Otherwise it will change he files that are base64 encoded (html, text) to jsonl format.
This change allows us in HPLT to take advantage of higher compression ratios when saving HTML in escaped inside a JSON, instead of base64, who has way worse compression ratios (as mentioned in #34).
To see the real changes of this PR: https://github.com/bitextor/warc2text/commit/f4e2a8303add5d10c115fb91a811efb6163b291b
> Move JSONL output to --stdout and allow file-based output with JSONL

- .gitmodules
- CMakeLists.txt
- src/CMakeLists.txt
- src/bilangwriter.cc
- src/bilangwriter.hh
- src/warcpreprocessor.cc
- warc2text_main.cc
Changes introduced with this new library migration:
- Strict UTF-8 encoding for JSON outputs.
- Different ways of managing UTF-8 encoding errors: replace errors, discard record, omit bad chars.
- Lower Boost minimum version (1.71 instead of 1.75). This allows compilation with the current boost in Ubuntu 22 and 20, which is 1.74.
Doing the PR with this branch because `nlohmann_json` branch commits are messed up.
> Replacing boost::json with nlohmann::json

- src/record.cc
- src/warcpreprocessor.cc
- src/warcpreprocessor.hh
Let's not forget this was already implemented in a branch. Should close #56
> Filter by http status code
